name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: [2019, 2020, 2021]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install -qq libuv1-dev -y
        python -m pip install --upgrade pip
        python -m pip install mys
    - name: Test year ${{matrix.year}}
      run: |
        mys -C ${{matrix.year}} test
