name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install -qq libuv1-dev -y
        python -m pip install --upgrade pip
        python -m pip install mys
    - name: Test
      run: |
        mys -C 2020 run 1 2 3 4 5 6 7 8 12 14 18 19 22
